stages:
  - deploy
  # - test

deploy:
  image: alpine:latest
  stage: deploy
  only:
    - develop
  before_script:
    - apk update
    - apk add openssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && git checkout $DEV_BRANCH && git pull && exit"
  after_script:
    - rm -rf ~/.ssh
#todo переделать, ранить тесты перед деплоем в своем контейнере, но без ssh доступа к гиту это невозможно
# test:
#   image: alpine:latest
#   stage: test
#   only:
#     - develop
#   before_script:
#     - apk update
#     - apk add openssh
#     - install -m 600 -D /dev/null ~/.ssh/id_rsa
#     - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#     - echo "$SSH_HOST"
#     - ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
#   script:
#     - ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && docker compose exec php-fpm php artisan test && exit"
#   after_script:
#     - rm -rf ~/.ssh

