server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html;
    client_max_body_size 10m;

    location /admin/ {
        try_files $uri $uri/ /admin/index.html;
    }

    location /mobile/ {
       try_files $uri $uri/ /mobile/index.html;
    }
    
    location /api/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /pulse {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /livewire/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /telescope {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /vendor/telescope/ {
        try_files $uri $uri/ /app.js?$query_string;
    }

    location /storage/images {
        alias /var/www/html/storage/app/public/images;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php-fpm:9000;
        fastcgi_connect_timeout 60;  # Increased timeout (10 minutes)
        fastcgi_send_timeout 60;   # Increased timeout (10 minutes)
        fastcgi_read_timeout 3600;
        proxy_read_timeout 3600;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}

