persistence true #постоянная запись
persistence_location /mosquitto/data

log_type subscribe
log_type unsubscribe
log_type websockets
log_type error
log_type warning
log_type notice
log_type debug
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout #пихать логи  в логи контейнера

password_file /mosquitto/config/password.conf
allow_anonymous false

# MQTT Default listener
listener 1884 0.0.0.0

# MQTT over WebSockets
listener 9001 0.0.0.0
protocol websockets
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
